In [ ]:
import pandas as pd
import json
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import pytz
import requests
import re
import psycopg2

from functions import read_db_credentials, connect_to_db, load_json_data_from_db_as_json, save_df_to_db, data_from_data_sink

In [ ]:
# def read_db_credentials(path="data/config.txt"):
#     creds = {}
#     with open(path, "r") as f:
#         for line in f:
#             key, value = line.strip().split("=")
#             creds[key] = value
#     return creds


# def connect_to_db(creds):
#     return psycopg2.connect(
#         host=creds["host"],
#         port=creds["port"],
#         dbname=creds["database"],
#         user=creds["user"],
#         password=creds["password"]
#     )
# def data_from_data_sink(query):
#     creds = read_db_credentials()
#     conn = connect_to_db(creds)
#     cur = conn.cursor()
    
#     df = pd.read_sql_query(query, conn)
    
#     conn.close()
    
#     return df

# def save_df_to_db(df, table_name, conflict_column='user_number'):
#     creds = read_db_credentials()
#     conn = connect_to_db(creds)
#     cursor = conn.cursor()
    
#     df = df.where(pd.notnull(df), None)  # Replace NaN with None for SQL

#     columns = list(df.columns)
#     column_names = ', '.join(columns)
#     placeholders = ', '.join(['%s'] * len(columns))

#     # Set update expression for each column
#     update_assignments = ', '.join([f"{col} = EXCLUDED.{col}" for col in columns if col != conflict_column])

#     insert_query = f"""
#         INSERT INTO {table_name} ({column_names})
#         VALUES ({placeholders})
#         ON CONFLICT ({conflict_column})
#         DO UPDATE SET {update_assignments};
#     """

#     for _, row in df.iterrows():
#         cursor.execute(insert_query, row.tolist())

#     conn.commit()
#     cursor.close()
#     conn.close()
#     return "saved (with upsert)"

    
# def load_json_data_from_db_as_json(user, source ):
#     creds = read_db_credentials()
#     conn = connect_to_db(creds)

#     # query = f"SELECT raw_json FROM fact_raw_data WHERE data_source = '{source}' AND user_number = {user} ;"
    
#     cursor = conn.cursor()
#     cursor.execute(query)
#     result = cursor.fetchone()
#     conn.close()
#     #return (result)
#     # # Parsen der JSON-Inhalte aus der 'data'-Spalte
#     parsed_data = result[0] if result else {}


#     # # Rückgabe als JSON-String (optional indent für Lesbarkeit)
#     return parsed_data

In [28]:
with open("data/cur_user_selected.txt", "r", encoding="utf-8") as f:
    user = int(f.read().strip())


sptfy_data = load_json_data_from_db_as_json(user, "spotify")
print(sptfy_data)

{'extracted_at': '2025-06-28T22:03:43.782525Z', 'user_profile': {'id': 'dave23042000', 'display_name': 'dave23042000', 'country': 'DE', 'product': 'premium'}, 'top_artists': [{'id': '08GQAI4eElDnROBrJRGE0X', 'name': 'Fleetwood Mac', 'genres': ['classic rock', 'yacht rock', 'soft rock'], 'popularity': 85, 'followers': 13335667, 'spotify_url': 'https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X'}, {'id': '3nwKjjo8rZtE0rRVgz4OPB', 'name': 'S.T.S', 'genres': ['schlager', 'neue deutsche welle', 'schlagerparty'], 'popularity': 54, 'followers': 251338, 'spotify_url': 'https://open.spotify.com/artist/3nwKjjo8rZtE0rRVgz4OPB'}, {'id': '4vWQjpI68kWBNkXOEbi1D6', 'name': 'Rainhard Fendrich', 'genres': ['neue deutsche welle', 'schlager', 'schlagerparty', 'german pop'], 'popularity': 52, 'followers': 244433, 'spotify_url': 'https://open.spotify.com/artist/4vWQjpI68kWBNkXOEbi1D6'}, {'id': '0WwSkZ7LtFUFjGjMZBMt6T', 'name': 'Dire Straits', 'genres': ['classic rock'], 'popularity': 81, 'followers': 8538975, 'spotify_url': 'https://open.spotify.com/artist/0WwSkZ7LtFUFjGjMZBMt6T'}, {'id': '6LjOtJ9U1bUN331ChKrw8q', 'name': 'Udo West', 'genres': ['german indie', 'neue deutsche welle'], 'popularity': 43, 'followers': 5447, 'spotify_url': 'https://open.spotify.com/artist/6LjOtJ9U1bUN331ChKrw8q'}, {'id': '1HIExD1wI4d0Y6Ehzl0YII', 'name': 'Wolfgang Ambros', 'genres': ['neue deutsche welle', 'schlager', 'singer-songwriter'], 'popularity': 50, 'followers': 148342, 'spotify_url': 'https://open.spotify.com/artist/1HIExD1wI4d0Y6Ehzl0YII'}, {'id': '3WrFJ7ztbogyGnTHbHJFl2', 'name': 'The Beatles', 'genres': ['classic rock', 'psychedelic rock'], 'popularity': 86, 'followers': 30120783, 'spotify_url': 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2'}, {'id': '6Kg9EvjSnEm5swmrvWCJyB', 'name': 'Wanda', 'genres': ['german indie', 'german pop'], 'popularity': 54, 'followers': 266593, 'spotify_url': 'https://open.spotify.com/artist/6Kg9EvjSnEm5swmrvWCJyB'}, {'id': '4tX2TplrkIP4v05BNC903e', 'name': 'Tom Petty and the Heartbreakers', 'genres': ['classic rock'], 'popularity': 72, 'followers': 3018482, 'spotify_url': 'https://open.spotify.com/artist/4tX2TplrkIP4v05BNC903e'}, {'id': '0C0XlULifJtAgn6ZNCW2eu', 'name': 'The Killers', 'genres': ['alternative rock'], 'popularity': 80, 'followers': 7852914, 'spotify_url': 'https://open.spotify.com/artist/0C0XlULifJtAgn6ZNCW2eu'}, {'id': '0hLd40hVpRDGENe4KGZLnW', 'name': 'Falco', 'genres': ['neue deutsche welle'], 'popularity': 62, 'followers': 626940, 'spotify_url': 'https://open.spotify.com/artist/0hLd40hVpRDGENe4KGZLnW'}, {'id': '3RCOgmbS8WtFSMKQAholxE', 'name': 'Rainald Grebe', 'genres': ['singer-songwriter'], 'popularity': 40, 'followers': 44663, 'spotify_url': 'https://open.spotify.com/artist/3RCOgmbS8WtFSMKQAholxE'}, {'id': '2F8GvYuY0lfZNYu45dY6gJ', 'name': 'Die Toten Hosen', 'genres': ['german pop', 'neue deutsche welle'], 'popularity': 65, 'followers': 1592858, 'spotify_url': 'https://open.spotify.com/artist/2F8GvYuY0lfZNYu45dY6gJ'}, {'id': '4gzpq5DPGxSnKTe4SA8HAU', 'name': 'Coldplay', 'genres': [], 'popularity': 92, 'followers': 58898554, 'spotify_url': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}, {'id': '1xmmqPgPSW7jn8rs6fH0e2', 'name': 'Austria 3', 'genres': [], 'popularity': 39, 'followers': 56554, 'spotify_url': 'https://open.spotify.com/artist/1xmmqPgPSW7jn8rs6fH0e2'}, {'id': '0MZ55DwuMQ1B2TXq9lcrE4', 'name': 'Kraftklub', 'genres': ['german indie', 'german pop'], 'popularity': 66, 'followers': 863334, 'spotify_url': 'https://open.spotify.com/artist/0MZ55DwuMQ1B2TXq9lcrE4'}, {'id': '7oPftvlwr6VrsViSDV7fJY', 'name': 'Green Day', 'genres': ['punk', 'pop punk'], 'popularity': 84, 'followers': 16791656, 'spotify_url': 'https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY'}, {'id': '3utZ2yeQk0Z3BCOBWP7Vlu', 'name': 'CRO', 'genres': ['german hip hop', 'german pop', 'german indie'], 'popularity': 73, 'followers': 2729326, 'spotify_url': 'https://open.spotify.com/artist/3utZ2yeQk0Z3BCOBWP7Vlu'}, {'id': '1dfeR4HaWDbWqFHLkxsg1d', 'name': 'Queen', 'genres': ['classic rock', 'rock', 'glam rock'], 'popularity': 86, 'followers': 54207403, 'spotify_url': 'https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d'}, {'id': '5YGY8feqx7naU7z4HrwZM6', 'name': 'Miley Cyrus', 'genres': [], 'popularity': 86, 'followers': 26117669, 'spotify_url': 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6'}], 'recently_played': [{'id': '0e0caZUnWgyqFDsf2khkWH', 'name': 'Wahre Liebe', 'popularity': 19, 'duration_ms': 195546, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/0e0caZUnWgyqFDsf2khkWH', 'artists': [{'id': '5xXbh3Wr8IDemhSrxHU2vQ', 'name': 'Virginia Jetzt!'}], 'album': {'id': '6CkaVGQlp9LXVuAZ5Hx1Xf', 'name': 'Anfänger', 'release_date': '2004-01-01'}, 'played_at': '2025-06-28T19:49:19.133Z', 'play_count': 1}, {'id': '2PzU4IB8Dr6mxV3lHuaG34', 'name': "(I Can't Get No) Satisfaction - Mono", 'popularity': 80, 'duration_ms': 222813, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/2PzU4IB8Dr6mxV3lHuaG34', 'artists': [{'id': '22bE4uQ6baNwSHPVcDxLCe', 'name': 'The Rolling Stones'}], 'album': {'id': '2Q5MwpTmtjscaS34mJFXQQ', 'name': 'Out Of Our Heads', 'release_date': '1965-07-30'}, 'played_at': '2025-06-28T19:45:56.944Z', 'play_count': 1}, {'id': '7FkyQsWH9mmxoYLCNj4f8y', 'name': 'Fire Water Burn', 'popularity': 63, 'duration_ms': 291800, 'explicit': True, 'spotify_url': 'https://open.spotify.com/track/7FkyQsWH9mmxoYLCNj4f8y', 'artists': [{'id': '6nDLku5uL3ou60kvCGZorh', 'name': 'Bloodhound Gang'}], 'album': {'id': '12Vg9jAQ2maGpRMY1Lqm9f', 'name': 'One Fierce Beer Coaster', 'release_date': '1996-01-01'}, 'played_at': '2025-06-28T19:42:15.298Z', 'play_count': 1}, {'id': '7zok5fWOsWWcHnWUTfB0Zy', 'name': 'Tanto amore', 'popularity': 42, 'duration_ms': 188640, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/7zok5fWOsWWcHnWUTfB0Zy', 'artists': [{'id': '6LjOtJ9U1bUN331ChKrw8q', 'name': 'Udo West'}], 'album': {'id': '1zPh3pPuDMcIzd3vyjr1kD', 'name': "Let's Go West!", 'release_date': '2022-10-08'}, 'played_at': '2025-06-28T19:37:21.552Z', 'play_count': 1}, {'id': '2m1hi0nfMR9vdGC8UcrnwU', 'name': 'All The Small Things', 'popularity': 85, 'duration_ms': 167066, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/2m1hi0nfMR9vdGC8UcrnwU', 'artists': [{'id': '6FBDaR13swtiWwGhX1WQsP', 'name': 'blink-182'}], 'album': {'id': '652N05EcNH1a4bIlUixQE2', 'name': 'Enema Of The State', 'release_date': '1999-06-01'}, 'played_at': '2025-06-28T19:34:11.944Z', 'play_count': 1}, {'id': '5vdp5UmvTsnMEMESIF2Ym7', 'name': 'Another One Bites The Dust - Remastered 2011', 'popularity': 84, 'duration_ms': 214653, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/5vdp5UmvTsnMEMESIF2Ym7', 'artists': [{'id': '1dfeR4HaWDbWqFHLkxsg1d', 'name': 'Queen'}], 'album': {'id': '58alCatewkjNm9IM1Ucj67', 'name': 'The Game (2011 Remaster)', 'release_date': '1980-06-27'}, 'played_at': '2025-06-28T19:31:28.397Z', 'play_count': 1}, {'id': '3v9xlH6BpmRbqL7hgNJhfT', 'name': 'I Get Around (Mono)', 'popularity': 72, 'duration_ms': 134386, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/3v9xlH6BpmRbqL7hgNJhfT', 'artists': [{'id': '3oDbviiivRWhXwIE8hxkVV', 'name': 'The Beach Boys'}], 'album': {'id': '6GnzWMUyNEETCq6eftD98v', 'name': 'All Summer Long (Mono & Stereo)', 'release_date': '1964-07-13'}, 'played_at': '2025-06-28T19:27:49.497Z', 'play_count': 1}, {'id': '7E1gZbAh7yzpXH6SUsN2Rr', 'name': 'Beautiful World', 'popularity': 48, 'duration_ms': 244640, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/7E1gZbAh7yzpXH6SUsN2Rr', 'artists': [{'id': '5mxB08ktCukEhGMg2YZeEv', 'name': 'Colin Hay'}], 'album': {'id': '1Nz5qR5kcOBV4ByER6M2OE', 'name': 'Going Somewhere', 'release_date': '2000'}, 'played_at': '2025-06-28T19:25:37.658Z', 'play_count': 1}, {'id': '3qiyyUfYe7CRYLucrPmulD', 'name': "Baba O'Riley", 'popularity': 79, 'duration_ms': 300400, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/3qiyyUfYe7CRYLucrPmulD', 'artists': [{'id': '67ea9eGLXYMsO2eYQRui3w', 'name': 'The Who'}], 'album': {'id': '5MqyhhHbT13zsloD3uHhlQ', 'name': "Who's Next (Deluxe Edition)", 'release_date': '1971-08-14'}, 'played_at': '2025-06-28T19:21:29.619Z', 'play_count': 1}, {'id': '1QFh8OH1e78dGd3VyJZCAC', 'name': "Boys Don't Cry", 'popularity': 80, 'duration_ms': 155973, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/1QFh8OH1e78dGd3VyJZCAC', 'artists': [{'id': '7bu3H8JO7d0UbMoVzbo70s', 'name': 'The Cure'}], 'album': {'id': '0jYmAPQezr1aG75KerJCdG', 'name': 'Three Imaginary Boys', 'release_date': '1979-05-11'}, 'played_at': '2025-06-28T19:16:30.320Z', 'play_count': 1}, {'id': '0FRAPPQDNqcaHyCR7Jx8Zu', 'name': 'Fäuste hoch', 'popularity': 59, 'duration_ms': 210400, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/0FRAPPQDNqcaHyCR7Jx8Zu', 'artists': [{'id': '2xU1DzacdEgPLClHtH48E1', 'name': 'Irie Révoltés'}], 'album': {'id': '4yuFY4QnDIVkCxdhOBA8mX', 'name': 'Irie Révoltés', 'release_date': '2015-06-19'}, 'played_at': '2025-06-28T19:13:54.263Z', 'play_count': 1}, {'id': '4VrWlk8IQxevMvERoX08iC', 'name': 'Chandelier', 'popularity': 84, 'duration_ms': 216120, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/4VrWlk8IQxevMvERoX08iC', 'artists': [{'id': '5WUlDfRSoLAfcVSX1WnrxN', 'name': 'Sia'}], 'album': {'id': '3xFSl9lIRaYXIYkIn3OIl9', 'name': '1000 Forms Of Fear', 'release_date': '2014-07-04'}, 'played_at': '2025-06-28T07:45:10.710Z', 'play_count': 1}, {'id': '22skzmqfdWrjJylampe0kt', 'name': "Can't Hold Us (feat. Ray Dalton)", 'popularity': 88, 'duration_ms': 258431, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/22skzmqfdWrjJylampe0kt', 'artists': [{'id': '3JhNCzhSMTxs9WLGJJxWOY', 'name': 'Macklemore'}, {'id': '5mZJerulcERBZV7xnhrVp1', 'name': 'Ryan Lewis'}, {'id': '5BcAKTbp20cv7tC5VqPFoC', 'name': 'Macklemore & Ryan Lewis'}, {'id': '4e0nWw2r4BoQSKPQ2zpU13', 'name': 'Ray Dalton'}], 'album': {'id': '5QWHes9ODwn42DHTifGkXd', 'name': 'The Heist', 'release_date': '2012-10-09'}, 'played_at': '2025-06-28T07:40:21.765Z', 'play_count': 1}, {'id': '5Ohxk2dO5COHF1krpoPigN', 'name': 'Sign of the Times', 'popularity': 88, 'duration_ms': 340706, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/5Ohxk2dO5COHF1krpoPigN', 'artists': [{'id': '6KImCVD70vtIoJWnq6nGn3', 'name': 'Harry Styles'}], 'album': {'id': '1FZKIm3JVDCxTchXDo5jOV', 'name': 'Harry Styles', 'release_date': '2017-05-12'}, 'played_at': '2025-06-28T07:33:35.700Z', 'play_count': 1}, {'id': '6RUKPb4LETWmmr3iAEQktW', 'name': 'Something Just Like This', 'popularity': 91, 'duration_ms': 247160, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/6RUKPb4LETWmmr3iAEQktW', 'artists': [{'id': '69GGBxA162lTqCwzJG5jLp', 'name': 'The Chainsmokers'}, {'id': '4gzpq5DPGxSnKTe4SA8HAU', 'name': 'Coldplay'}], 'album': {'id': '4JPguzRps3kuWDD5GS6oXr', 'name': 'Memories...Do Not Open', 'release_date': '2017-04-07'}, 'played_at': '2025-06-28T07:26:44.519Z', 'play_count': 1}, {'id': '1Jaah2tmN9Hv81A87KZ1MU', 'name': 'Torn', 'popularity': 83, 'duration_ms': 244666, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/1Jaah2tmN9Hv81A87KZ1MU', 'artists': [{'id': '0dlOr0VIysztGWvU1dpjmP', 'name': 'Natalie Imbruglia'}], 'album': {'id': '38alWeQVP9UUAGJvLptys9', 'name': 'Left Of The Middle', 'release_date': '1997-11-10'}, 'played_at': '2025-06-28T07:20:12.899Z', 'play_count': 1}, {'id': '6si71supnBUhddjR2FJc2L', 'name': 'White Flag', 'popularity': 80, 'duration_ms': 240040, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/6si71supnBUhddjR2FJc2L', 'artists': [{'id': '2mpeljBig2IXLXRAFO9AAs', 'name': 'Dido'}], 'album': {'id': '7HlZFlk0jJq3Bb03AOyMTE', 'name': 'Life For Rent', 'release_date': '2003'}, 'played_at': '2025-06-28T07:10:02.741Z', 'play_count': 1}, {'id': '2vwlzO0Qp8kfEtzTsCXfyE', 'name': 'Wrecking Ball', 'popularity': 84, 'duration_ms': 221360, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/2vwlzO0Qp8kfEtzTsCXfyE', 'artists': [{'id': '5YGY8feqx7naU7z4HrwZM6', 'name': 'Miley Cyrus'}], 'album': {'id': '3RDqXDc1bAETps54MSSOW0', 'name': 'Bangerz (Deluxe Version)', 'release_date': '2013-10-04'}, 'played_at': '2025-06-28T07:05:55.040Z', 'play_count': 1}, {'id': '3U5JVgI2x4rDyHGObzJfNf', 'name': 'Unwritten', 'popularity': 91, 'duration_ms': 259333, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/3U5JVgI2x4rDyHGObzJfNf', 'artists': [{'id': '7o95ZoZt5ZYn31e9z1Hc0a', 'name': 'Natasha Bedingfield'}], 'album': {'id': '3PEzTAuPW5IjLJ58FzwQeL', 'name': 'Unwritten', 'release_date': '2004-08-30'}, 'played_at': '2025-06-28T07:02:13.677Z', 'play_count': 1}, {'id': '3xkHsmpQCBMytMJNiDf3Ii', 'name': 'Beautiful Things', 'popularity': 93, 'duration_ms': 180304, 'explicit': False, 'spotify_url': 'https://open.spotify.com/track/3xkHsmpQCBMytMJNiDf3Ii', 'artists': [{'id': '22wbnEMDvgVIAGdFeek6ET', 'name': 'Benson Boone'}], 'album': {'id': '168CdR21lfn0TTyw1Pkdcm', 'name': 'Fireworks & Rollerblades', 'release_date': '2024-04-05'}, 'played_at': '2025-06-28T06:57:53.276Z', 'play_count': 1}], 'collaborative_playlists': []}

In [29]:
# Top-Level Keys anzeigen
data = sptfy_data
import json

def print_json_structure(data, indent=0):
    spacer = "  " * indent
    if isinstance(data, dict):
        for key, value in data.items():
            print(f"{spacer}\"{key}\": ", end="")
            if isinstance(value, (dict, list)):
                print()
                print_json_structure(value, indent + 1)
            else:
                print(type(value).__name__)
    elif isinstance(data, list):
        print(f"{spacer}[")
        if data:
            print_json_structure(data[0], indent + 1)
        else:
            print(f"{'  ' * (indent + 1)}<empty>")
        print(f"{spacer}]")
    else:
        print(f"{spacer}{type(data).__name__}")

# JSON-Datei laden

# Struktur ausgeben
print_json_structure(data)

"extracted_at": str
"user_profile":
  "id": str
  "display_name": str
  "country": str
  "product": str
"top_artists":
  [
    "id": str
    "name": str
    "genres":
      [
        str
      ]
    "popularity": int
    "followers": int
    "spotify_url": str
  ]
"recently_played":
  [
    "id": str
    "name": str
    "popularity": int
    "duration_ms": int
    "explicit": bool
    "spotify_url": str
    "artists":
      [
        "id": str
        "name": str
      ]
    "album":
      "id": str
      "name": str
      "release_date": str
    "played_at": str
    "play_count": int
  ]
"collaborative_playlists":
  [
    <empty>
  ]

In [30]:
from collections import Counter
import requests

artist_genre_cache = {}  # Cache für Artist-Genres

def get_weighted_genres(track_query, target_artist):
    if target_artist.lower() in artist_genre_cache:
        return artist_genre_cache[target_artist.lower()]

    access_token = auth.get_token()
    headers = {"Authorization": f"Bearer {access_token}"}
    params = {"q": track_query, "type": "track", "limit": 20}
    response = requests.get("https://api.spotify.com/v1/search", headers=headers, params=params)
    data = response.json()

    genre_counter = Counter()
    total_artist_matches = 0

    for track in data.get("tracks", {}).get("items", []):
        matched_artist = next(
            (artist for artist in track["artists"] if artist["name"].lower() == target_artist.lower()), None
        )
        if matched_artist:
            total_artist_matches += 1
            artist_id = matched_artist["id"]
            artist_data = requests.get(f"https://api.spotify.com/v1/artists/{artist_id}", headers=headers).json()
            genres = artist_data.get("genres", [])
            genre_counter.update(genres)

    if total_artist_matches == 0 or not genre_counter:
        artist_genre_cache[target_artist.lower()] = {}
        return {}

    total_genre_mentions = sum(genre_counter.values())
    normalized_genres = {
        genre: round(count / total_genre_mentions, 3)
        for genre, count in genre_counter.items()
    }

    artist_genre_cache[target_artist.lower()] = normalized_genres
    return normalized_genres

In [31]:
import pandas as pd

def extract_recent_tracks(data: dict) -> pd.DataFrame:
    """
    Extracts track name, artist name, and play duration from a user's recently played Spotify data.

    :param data: Dictionary structured as described (with 'recently_played' list of tracks)
    :return: DataFrame with columns: track_name, artist_name, duration_ms
    """
    recently_played = data.get("recently_played", [])

    if not recently_played:
        return pd.DataFrame(columns=["track_name", "artist_name", "duration_ms"])

    rows = []
    for track in recently_played[:500]:  # Limit to first 500
        track_name = track.get("name", "NA")
        duration_ms = track.get("duration_ms", 0)
        artist_info = track.get("artists", [])
        timestamp = track.get("played_at", [])
        artist_name = artist_info[0].get("name") if artist_info else "Unknown"
        
        rows.append({
            "track_name": track_name,
            "artist_name": artist_name,
            "duration_ms": duration_ms,
            "timestamp": timestamp
        })

    return pd.DataFrame(rows)


df = extract_recent_tracks(sptfy_data)
print(df)

                                      track_name          artist_name  \
0                                    Wahre Liebe      Virginia Jetzt!
1           (I Can't Get No) Satisfaction - Mono   The Rolling Stones
2                                Fire Water Burn      Bloodhound Gang
3                                    Tanto amore             Udo West
4                           All The Small Things            blink-182
5   Another One Bites The Dust - Remastered 2011                Queen
6                            I Get Around (Mono)       The Beach Boys
7                                Beautiful World            Colin Hay
8                                   Baba O'Riley              The Who
9                                 Boys Don't Cry             The Cure
10                                   Fäuste hoch        Irie Révoltés
11                                    Chandelier                  Sia
12              Can't Hold Us (feat. Ray Dalton)           Macklemore
13                             Sign of the Times         Harry Styles
14                      Something Just Like This     The Chainsmokers
15                                          Torn    Natalie Imbruglia
16                                    White Flag                 Dido
17                                 Wrecking Ball          Miley Cyrus
18                                     Unwritten  Natasha Bedingfield
19                              Beautiful Things         Benson Boone

    duration_ms                 timestamp
0        195546  2025-06-28T19:49:19.133Z
1        222813  2025-06-28T19:45:56.944Z
2        291800  2025-06-28T19:42:15.298Z
3        188640  2025-06-28T19:37:21.552Z
4        167066  2025-06-28T19:34:11.944Z
5        214653  2025-06-28T19:31:28.397Z
6        134386  2025-06-28T19:27:49.497Z
7        244640  2025-06-28T19:25:37.658Z
8        300400  2025-06-28T19:21:29.619Z
9        155973  2025-06-28T19:16:30.320Z
10       210400  2025-06-28T19:13:54.263Z
11       216120  2025-06-28T07:45:10.710Z
12       258431  2025-06-28T07:40:21.765Z
13       340706  2025-06-28T07:33:35.700Z
14       247160  2025-06-28T07:26:44.519Z
15       244666  2025-06-28T07:20:12.899Z
16       240040  2025-06-28T07:10:02.741Z
17       221360  2025-06-28T07:05:55.040Z
18       259333  2025-06-28T07:02:13.677Z
19       180304  2025-06-28T06:57:53.276Z

In [32]:

from data.secrets import auth, client_secret
df["weightedGenres"] = df.apply(
    lambda row: get_weighted_genres(row['track_name'], row['artist_name']),
    axis=1
)

In [33]:
import requests
import base64

client_id = '8541e8dfc0fd4a86916d0d98cdb150ad'
client_secret = 'cade2256b5804831a11349f86e6a1784'

import requests
import base64
import time

class SpotifyAuth:
    def __init__(self, client_id, client_secret):
        self.client_id = client_id
        self.client_secret = client_secret
        self.access_token = None
        self.token_expires_at = 0  # Unix timestamp

    def _fetch_token(self):
        auth_str = f"{self.client_id}:{self.client_secret}"
        b64_auth_str = base64.b64encode(auth_str.encode()).decode()

        response = requests.post(
            "https://accounts.spotify.com/api/token",
            data={"grant_type": "client_credentials"},
            headers={"Authorization": f"Basic {b64_auth_str}"}
        )

        if response.status_code == 200:
            token_data = response.json()
            self.access_token = token_data["access_token"]
            # Spotify gibt Gültigkeit in Sekunden an (meist 3600)
            self.token_expires_at = time.time() + token_data.get("expires_in", 3600) - 60
        else:
            raise Exception(f"Fehler beim Abrufen des Tokens: {response.status_code} - {response.text}")


    def get_token(self):
        if not self.access_token or time.time() >= self.token_expires_at:
            self._fetch_token()
        return self.access_token
    

auth = SpotifyAuth(client_id = '8541e8dfc0fd4a86916d0d98cdb150ad',
client_secret = 'cade2256b5804831a11349f86e6a1784')

In [34]:
import pandas as pd
import re


# Regex-basierte Mapping-Regeln (von spezifisch zu allgemein)
REGEX_GENRE_TO_USER_TYPE = {
    # HIPHOP / RAP
    r".*\bhip hop\b.*": "hiphop_head",
    r".*\bgrime\b.*": "hiphop_head",
    r".*\bdrill\b.*": "hiphop_head",
    r".*\brap\b.*": "hiphop_head",
    r".*\burbaine\b.*": "hiphop_head",
    r".*\btrap\b.*": "hiphop_head",
    r".*\bgrime\b.*": "hiphop_head",
    r".*\buk grime\b.*": "hiphop_head",

    # ELECTRONIC
    r".*\bhouse\b.*": "electronic_addict",
    r".*\btrance\b.*": "electronic_addict",
    r".*\btechno\b.*": "electronic_addict",
    r".*\bbig room\b.*": "electronic_addict",
    r".*\bedm\b.*": "electronic_addict",
    r".*\belectronica\b.*": "electronic_addict",
    r".*\bdance\b.*": "electronic_addict",
    r".*\bdrum and bass\b.*": "electronic_addict",
    r".*\bfuture house\b.*": "electronic_addict",
    r".*\bprogressive house\b.*": "electronic_addict",
    r".*\btropical house\b.*": "electronic_addict",

    # POP
    r".*\bpop\b.*": "pop_lover",
    r".*\bsoft pop\b.*": "pop_lover",
    r".*\bart pop\b.*": "pop_lover",
    r".*\bindie pop\b.*": "pop_lover",
    r".*\bmodern pop\b.*": "pop_lover",
    r".*\bmoroccan pop\b.*": "pop_lover",
    r".*\begyptian pop\b.*": "pop_lover",
    r".*\bturkish pop\b.*": "pop_lover",
    r".*\blatin pop\b.*": "pop_lover",
    r".*\bk-pop\b.*": "pop_lover",
    r".*\bt-pop\b.*": "pop_lover",

    # INDIE / ALTERNATIVE
    r".*\bindie rock\b.*": "indie_explorer",
    r".*\balternative rock\b.*": "indie_explorer",
    r".*\bindie\b.*": "indie_explorer",
    r".*\bsinger-songwriter\b.*": "indie_explorer",
    r".*\bitalian singer-songwriter\b.*": "indie_explorer",

    # JAZZ
    r".*\bjazz\b.*": "jazz_purist",
    r".*\bfrench jazz\b.*": "jazz_purist",

    # CLASSICAL / MUSICAL
    r".*\bopera\b.*": "classical_connoisseur",
    r".*\bmusicals\b.*": "classical_connoisseur",
    r".*\bnueva trova\b.*": "classical_connoisseur",

    # ROCK
    r".*\brock\b.*": "rock_head",
    r".*\bgarage rock\b.*": "rock_head",

    # FUNK / SOUL / R&B
    r".*\br&b\b.*": "funk_soul_groover",
    r".*\bfrench r&b\b.*": "funk_soul_groover",
    r".*\bsoul\b.*": "funk_soul_groover",

    # COUNTRY / FOLK
    r".*\bfolk\b.*": "country_heart",
    r".*\bfolk pop\b.*": "country_heart",
    r".*\bmariachi\b.*": "country_heart",
    r".*\btrova\b.*": "country_heart",
    r".*\bbolero\b.*": "country_heart",

    # GLOBAL
    r".*\bafro.*": "global_vibes_fan",
    r".*\bdembow\b.*": "global_vibes_fan",
    r".*\blatin\b.*": "global_vibes_fan",
    r".*\bmoroccan rap\b.*": "global_vibes_fan",
    r".*\bkhaleeji\b.*": "global_vibes_fan",
    r".*\barabic hip hop\b.*": "global_vibes_fan",
    r".*\bvariet[eé] fran[aç]aise\b.*": "global_vibes_fan",
    r".*\bchanson\b.*": "global_vibes_fan",
    r".*\bitalo dance\b.*": "global_vibes_fan",
    r".*\barabesk\b.*": "global_vibes_fan",
    r".*\bra[iï]\b.*": "global_vibes_fan",
}


# Funktion zum Zuordnen via Regex
def map_genre_to_user_type(genre):
    for pattern, user_type in REGEX_GENRE_TO_USER_TYPE.items():
        if re.search(pattern, genre, re.IGNORECASE):
            return user_type
    return "mix_consumer"

In [35]:
rows = []
for _, row in df.iterrows():
    genres_dict = row.get("weightedGenres", {})
    if isinstance(genres_dict, dict):
        for genre, weight in genres_dict.items():
            rows.append({
                "trackName": row['track_name'],
                "artistName": row['artist_name'],
                "genre": genre,
                "weight": weight
            })

df_genres = pd.DataFrame(rows)
print(df_genres)
genre_summary = df_genres.groupby("genre", as_index=False)["weight"].sum().sort_values(by="weight", ascending=False)
genre_summary["user_type"] = genre_summary["genre"].apply(map_genre_to_user_type)


genre_summary["user_type"] = genre_summary["genre"].apply(map_genre_to_user_type)
print(genre_summary["genre"])
# Gruppieren und Gewicht aufsummieren
result = genre_summary.groupby("user_type", as_index=False)["weight"].sum()
total_weight = result ["weight"].sum()
result["normalized_weight"] = (result["weight"] / total_weight)*100
result_genre = result.sort_values("normalized_weight", ascending=False)
display(result.sort_values("normalized_weight", ascending=False))

                                       trackName          artistName  \
0           (I Can't Get No) Satisfaction - Mono  The Rolling Stones
1           (I Can't Get No) Satisfaction - Mono  The Rolling Stones
2                                    Tanto amore            Udo West
3                                    Tanto amore            Udo West
4                           All The Small Things           blink-182
5                           All The Small Things           blink-182
6                           All The Small Things           blink-182
7                           All The Small Things           blink-182
8                           All The Small Things           blink-182
9   Another One Bites The Dust - Remastered 2011               Queen
10  Another One Bites The Dust - Remastered 2011               Queen
11  Another One Bites The Dust - Remastered 2011               Queen
12                           I Get Around (Mono)      The Beach Boys
13                               Beautiful World           Colin Hay
14                                  Baba O'Riley             The Who
15                                  Baba O'Riley             The Who
16                                Boys Don't Cry            The Cure
17                                Boys Don't Cry            The Cure
18                                Boys Don't Cry            The Cure
19                                Boys Don't Cry            The Cure

                  genre  weight
0          classic rock   0.500
1                  rock   0.500
2          german indie   0.500
3   neue deutsche welle   0.500
4              pop punk   0.200
5                  punk   0.200
6                  rock   0.200
7            skate punk   0.200
8                   emo   0.200
9          classic rock   0.333
10                 rock   0.333
11            glam rock   0.333
12          baroque pop   1.000
13        drum and bass   1.000
14         classic rock   0.500
15                 rock   0.500
16             new wave   0.250
17            post-punk   0.250
18          gothic rock   0.250
19             darkwave   0.250
13                   rock
1            classic rock
0             baroque pop
3           drum and bass
5            german indie
8     neue deutsche welle
6               glam rock
2                darkwave
7             gothic rock
9                new wave
11              post-punk
4                     emo
10               pop punk
12                   punk
14             skate punk
Name: genre, dtype: object

           user_type  weight  normalized_weight
4          rock_head   3.449          43.117890
2       mix_consumer   1.850          23.127891
3          pop_lover   1.200          15.001875
0  electronic_addict   1.000          12.501563
1     indie_explorer   0.500           6.250781

In [36]:
import pandas as pd
from datetime import datetime
print(df)

# Zeitstempel umwandeln
df["timestamp"]= pd.to_datetime(df["timestamp"])

# Zeitstempel umwandeln
df["timestamp"]= pd.to_datetime(df["timestamp"])

# Minuten berechnen
df['minutes'] = df['duration_ms'] / 1000 / 60

# Datum extrahieren
df['date'] = df["timestamp"].dt.date

# Wochentag ermitteln: Montag = 0, Sonntag = 6
df['weekday'] = df["timestamp"].dt.weekday
df['is_weekend'] = df['weekday'] >= 5  # Samstag=5, Sonntag=6 → True

# Minuten pro Tag + Wochenende-Markierung
daily_minutes = df.groupby(['date', 'is_weekend'])['minutes'].sum().reset_index()

# Mittelwert berechnen
mean_per_group = daily_minutes.groupby('is_weekend')['minutes'].mean().reset_index()

# Lesbare Labels
mean_per_group['day_type'] = mean_per_group['is_weekend'].map({True: 'Weekend', False: 'Weekday'})
mean_per_group = mean_per_group[['day_type', 'minutes']]

print(daily_minutes)
print(mean_per_group)

# Tageszeit-Funktion
def get_day_part(hour):
    if 5 <= hour < 12:
        return "morning"
    elif 12 <= hour < 17:
        return "midday"
    elif 17 <= hour < 23:
        return "evening"
    else:
        return "night"

# Attribute berechnen
df['date'] = df["timestamp"].dt.date
df['weekday'] = df["timestamp"].dt.weekday  # Monday = 0
df['is_weekend'] = df['weekday'] >= 5
df['day_part'] = df["timestamp"].dt.hour.apply(get_day_part)

# Aggregation: Minuten pro Tagtyp und Tageszeit
df['day_type'] = df['is_weekend'].map({True: 'Weekend', False: 'Weekday'})
print(df)
# Gruppenbasierte Mittelwerte berechnen
grouped = df.groupby(['date','day_type', 'day_part'])['minutes'].sum().reset_index().groupby(['day_type', 'day_part'])['minutes'].mean().reset_index()


print(grouped)

                                      track_name          artist_name  \
0                                    Wahre Liebe      Virginia Jetzt!
1           (I Can't Get No) Satisfaction - Mono   The Rolling Stones
2                                Fire Water Burn      Bloodhound Gang
3                                    Tanto amore             Udo West
4                           All The Small Things            blink-182
5   Another One Bites The Dust - Remastered 2011                Queen
6                            I Get Around (Mono)       The Beach Boys
7                                Beautiful World            Colin Hay
8                                   Baba O'Riley              The Who
9                                 Boys Don't Cry             The Cure
10                                   Fäuste hoch        Irie Révoltés
11                                    Chandelier                  Sia
12              Can't Hold Us (feat. Ray Dalton)           Macklemore
13                             Sign of the Times         Harry Styles
14                      Something Just Like This     The Chainsmokers
15                                          Torn    Natalie Imbruglia
16                                    White Flag                 Dido
17                                 Wrecking Ball          Miley Cyrus
18                                     Unwritten  Natasha Bedingfield
19                              Beautiful Things         Benson Boone

    duration_ms                 timestamp  \
0        195546  2025-06-28T19:49:19.133Z
1        222813  2025-06-28T19:45:56.944Z
2        291800  2025-06-28T19:42:15.298Z
3        188640  2025-06-28T19:37:21.552Z
4        167066  2025-06-28T19:34:11.944Z
5        214653  2025-06-28T19:31:28.397Z
6        134386  2025-06-28T19:27:49.497Z
7        244640  2025-06-28T19:25:37.658Z
8        300400  2025-06-28T19:21:29.619Z
9        155973  2025-06-28T19:16:30.320Z
10       210400  2025-06-28T19:13:54.263Z
11       216120  2025-06-28T07:45:10.710Z
12       258431  2025-06-28T07:40:21.765Z
13       340706  2025-06-28T07:33:35.700Z
14       247160  2025-06-28T07:26:44.519Z
15       244666  2025-06-28T07:20:12.899Z
16       240040  2025-06-28T07:10:02.741Z
17       221360  2025-06-28T07:05:55.040Z
18       259333  2025-06-28T07:02:13.677Z
19       180304  2025-06-28T06:57:53.276Z

                                       weightedGenres
0                                                  {}
1                  {'classic rock': 0.5, 'rock': 0.5}
2                                                  {}
3   {'german indie': 0.5, 'neue deutsche welle': 0.5}
4   {'pop punk': 0.2, 'punk': 0.2, 'rock': 0.2, 's...
5   {'classic rock': 0.333, 'rock': 0.333, 'glam r...
6                                {'baroque pop': 1.0}
7                              {'drum and bass': 1.0}
8                  {'classic rock': 0.5, 'rock': 0.5}
9   {'new wave': 0.25, 'post-punk': 0.25, 'gothic ...
10                                                 {}
11                                                 {}
12                                                 {}
13                                                 {}
14                                                 {}
15                                                 {}
16                                                 {}
17                                                 {}
18                                                 {}
19                                                 {}
         date  is_weekend   minutes
0  2025-06-28        True  75.57395
  day_type   minutes
0  Weekend  75.57395
                                      track_name          artist_name  \
0                                    Wahre Liebe      Virginia Jetzt!
1           (I Can't Get No) Satisfaction - Mono   The Rolling Stones
2                                Fire Water Burn      Bloodhound Gang
3                                    Tanto amore             Udo West
4                           All The Small Things            blink-182
5   Another One Bites The Dust - Remastered 2011                Queen
6                            I Get Around (Mono)       The Beach Boys
7                                Beautiful World            Colin Hay
8                                   Baba O'Riley              The Who
9                                 Boys Don't Cry             The Cure
10                                   Fäuste hoch        Irie Révoltés
11                                    Chandelier                  Sia
12              Can't Hold Us (feat. Ray Dalton)           Macklemore
13                             Sign of the Times         Harry Styles
14                      Something Just Like This     The Chainsmokers
15                                          Torn    Natalie Imbruglia
16                                    White Flag                 Dido
17                                 Wrecking Ball          Miley Cyrus
18                                     Unwritten  Natasha Bedingfield
19                              Beautiful Things         Benson Boone

    duration_ms                        timestamp  \
0        195546 2025-06-28 19:49:19.133000+00:00
1        222813 2025-06-28 19:45:56.944000+00:00
2        291800 2025-06-28 19:42:15.298000+00:00
3        188640 2025-06-28 19:37:21.552000+00:00
4        167066 2025-06-28 19:34:11.944000+00:00
5        214653 2025-06-28 19:31:28.397000+00:00
6        134386 2025-06-28 19:27:49.497000+00:00
7        244640 2025-06-28 19:25:37.658000+00:00
8        300400 2025-06-28 19:21:29.619000+00:00
9        155973 2025-06-28 19:16:30.320000+00:00
10       210400 2025-06-28 19:13:54.263000+00:00
11       216120 2025-06-28 07:45:10.710000+00:00
12       258431 2025-06-28 07:40:21.765000+00:00
13       340706 2025-06-28 07:33:35.700000+00:00
14       247160 2025-06-28 07:26:44.519000+00:00
15       244666 2025-06-28 07:20:12.899000+00:00
16       240040 2025-06-28 07:10:02.741000+00:00
17       221360 2025-06-28 07:05:55.040000+00:00
18       259333 2025-06-28 07:02:13.677000+00:00
19       180304 2025-06-28 06:57:53.276000+00:00

                                       weightedGenres   minutes        date  \
0                                                  {}  3.259100  2025-06-28
1                  {'classic rock': 0.5, 'rock': 0.5}  3.713550  2025-06-28
2                                                  {}  4.863333  2025-06-28
3   {'german indie': 0.5, 'neue deutsche welle': 0.5}  3.144000  2025-06-28
4   {'pop punk': 0.2, 'punk': 0.2, 'rock': 0.2, 's...  2.784433  2025-06-28
5   {'classic rock': 0.333, 'rock': 0.333, 'glam r...  3.577550  2025-06-28
6                                {'baroque pop': 1.0}  2.239767  2025-06-28
7                              {'drum and bass': 1.0}  4.077333  2025-06-28
8                  {'classic rock': 0.5, 'rock': 0.5}  5.006667  2025-06-28
9   {'new wave': 0.25, 'post-punk': 0.25, 'gothic ...  2.599550  2025-06-28
10                                                 {}  3.506667  2025-06-28
11                                                 {}  3.602000  2025-06-28
12                                                 {}  4.307183  2025-06-28
13                                                 {}  5.678433  2025-06-28
14                                                 {}  4.119333  2025-06-28
15                                                 {}  4.077767  2025-06-28
16                                                 {}  4.000667  2025-06-28
17                                                 {}  3.689333  2025-06-28
18                                                 {}  4.322217  2025-06-28
19                                                 {}  3.005067  2025-06-28

    weekday  is_weekend day_part day_type
0         5        True  evening  Weekend
1         5        True  evening  Weekend
2         5        True  evening  Weekend
3         5        True  evening  Weekend
4         5        True  evening  Weekend
5         5        True  evening  Weekend
6         5        True  evening  Weekend
7         5        True  evening  Weekend
8         5        True  evening  Weekend
9         5        True  evening  Weekend
10        5        True  evening  Weekend
11        5        True  morning  Weekend
12        5        True  morning  Weekend
13        5        True  morning  Weekend
14        5        True  morning  Weekend
15        5        True  morning  Weekend
16        5        True  morning  Weekend
17        5        True  morning  Weekend
18        5        True  morning  Weekend
19        5        True  morning  Weekend
  day_type day_part   minutes
0  Weekend  evening  38.77195
1  Weekend  morning  36.80200

In [37]:

type_mapping = []

type_mapping.append({
    "listener_type": "late_night_listener",
    "day_type": "Weekday",
    "day_part": "night",
    "weight": 1.0
})
type_mapping.append({
    "listener_type": "weekwnd_party_listener",
    "day_type": "Weekend",
    "day_part": "night",
    "weight": 1.0
})

# Weekday Focus Day
type_mapping.append({
    "listener_type": "working_focus_listener",
    "day_type": "Weekday",
    "day_part": "morning",
    "weight": 0.5
})
type_mapping.append({
    "listener_type": "working_focus_listener",
    "day_type": "Weekday",
    "day_part": "midday",
    "weight": 0.5
})

# Weekend Focus Day
type_mapping.append({
    "listener_type": "weekend_breakfast_listener",
    "day_type": "Weekend",
    "day_part": "morning",
    "weight": 0.5
})
type_mapping.append({
    "listener_type": "weekend_breakfast_listener",
    "day_type": "Weekend",
    "day_part": "midday",
    "weight": 0.5
})

# Weekday Evening
type_mapping.append({
    "listener_type": "weekday_sundown_listener",
    "day_type": "Weekday",
    "day_part": "evening",
    "weight": 1.0
})

# Weekend Evening
type_mapping.append({
    "listener_type": "weekend_prime_time_listener",
    "day_type": "Weekend",
    "day_part": "evening",
    "weight": 1.0
})

map_df = pd.DataFrame(type_mapping)
merged = pd.merge(grouped, map_df, on=["day_type", "day_part"], how="inner")
merged["weighted_minutes"] = merged["minutes"] * merged["weight"]
result = merged.groupby("listener_type")["weighted_minutes"].sum().reset_index()
result = result.sort_values(by="weighted_minutes", ascending=False).reset_index(drop=True)
total = result["weighted_minutes"].sum()
result["normalized"] = result["weighted_minutes"] / total
# Sicherstellen, dass mindestens 3 Zeilen vorhanden sind
import numpy as np
missing_rows = max(0, 3 - len(result))
if missing_rows > 0:
    empty_rows = pd.DataFrame({
        "listener_type": [np.nan] * missing_rows,
        "weighted_minutes": [np.nan] * missing_rows,
        "normalized": [np.nan] * missing_rows
    })
    result = pd.concat([result, empty_rows], ignore_index=True)

print(result)

                 listener_type  weighted_minutes  normalized
0  weekend_prime_time_listener          38.77195    0.678152
1   weekend_breakfast_listener          18.40100    0.321848
2                          NaN               NaN         NaN

| Type                                  | Description                                                                     | Rule                                                       |
| ------------------------------------- | ------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| 🎧 **late\_night\_listener**          | Mostly listens at night – prefers chill, lo-fi, or introspective music.         | Night listening ≥ 40% of total time                        |
| ☀️ **weekday\_focus\_day\_listener**  | Listens primarily during mornings and midday on weekdays – productive sessions. | Morning + midday ≥ 50%, with more time on weekdays         |
| ☀️ **weekend\_focus\_day\_listener**  | Listens mainly in the morning or midday on weekends – calm and balanced mood.   | Morning + midday ≥ 50%, with more time on weekends         |
| 🌆 **weekday\_prime\_time\_streamer** | Prefers evening listening on weekdays – post-work, gym, or relaxation music.    | Evening is dominant, and weekday evening > weekend evening |
| 🌆 **weekend\_prime\_time\_streamer** | Tunes in most during weekend evenings – party vibes or social listening.        | Evening is dominant, and weekend evening > weekday evening |
| 🎛️ **eclectic\_rhythm\_fan**         | No dominant time pattern – diverse and varied music preferences.                | No strong dominance across time blocks                     |
| 🔇 **silent\_type**                   | No activity or not enough data for classification.                              | Total listening time is 0                                  |

In [38]:
result_genre

           user_type  weight  normalized_weight
4          rock_head   3.449          43.117890
2       mix_consumer   1.850          23.127891
3          pop_lover   1.200          15.001875
0  electronic_addict   1.000          12.501563
1     indie_explorer   0.500           6.250781

In [39]:

res = pd.DataFrame([{
    "user_number": user,
    "sptfy_gnr_type_1": f'{result_genre["user_type"][0]} ({round(result_genre["normalized_weight"][0],0)}%)',
    "sptfy_gnr_type_2": f'{result_genre["user_type"][1]} ({round(result_genre["normalized_weight"][1],0)}%)',
    "sptfy_gnr_type_3": f'{result_genre["user_type"][2]} ({round(result_genre["normalized_weight"][2],0)}%)',
    "sptfy_lt_type_1": f'{result["listener_type"][0]} ({round(result["normalized"][0],2)*100}%)',
    "sptfy_lt_type_2": f'{result["listener_type"][1]} ({round(result["normalized"][1],2)*100}%)',
    "sptfy_lt_type_3": f'{result["listener_type"][2]} ({round(result["normalized"][2],2)*100}%)'
   
}])
print(res)

save_df_to_db(res, "dim_spotify")

   user_number           sptfy_gnr_type_1       sptfy_gnr_type_2  \
0           10  electronic_addict (13.0%)  indie_explorer (6.0%)

       sptfy_gnr_type_3                      sptfy_lt_type_1  \
0  mix_consumer (23.0%)  weekend_prime_time_listener (68.0%)

                      sptfy_lt_type_2 sptfy_lt_type_3
0  weekend_breakfast_listener (32.0%)      nan (nan%)

'saved (with upsert)'